server:
  port: 8080
spring:
  profiles:
    # 运行的环境
    active: local
  application:
    # 项目名
    name: hichat
  datasource:
    url: jdbc:mysql://${hichat.mysql.ip}:${hichat.mysql.port}/${hichat.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${hichat.mysql.username}
    password: ${hichat.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis服务器地址
    host: ${hichat.redis.host}
    # Redis服务器端口号
    port: ${hichat.redis.port}
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: ${hichat.redis.password}
  jackson:
    serialization:
      write-dates-as-timestamps: true
# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 下划线转换驼峰
    map-underscore-to-camel-case: true
# 微信公众号
wx:
  mp:
    useRedis: false
    redisConfig:
      host: 127.0.0.1
      port: 6379
      timeout: 2000
    #    callback: http://f4cd-113-92-129-127.ngrok.io
    callback: ${hichat.wx.callback}
    configs:
      - appId: ${hichat.wx.appId} # 第一个公众号的appid
        secret: ${hichat.wx.secret} # 公众号的appsecret
        token: ${hichat.wx.token} # 接口配置里的Token值
        aesKey: ${hichat.wx.aesKey} # 接口配置里的EncodingAESKey值
# jwt密钥
jwt:
  secret: ${hichat.jwt.secret}